@startuml
title UC1: Game Initialization Sequence Diagram

actor User
participant ":GameView" as GameView
participant ":FXGameView" as FXGameView
participant ":GameController" as GameController
participant ":YutnoriApplication" as YutnoriApplication
participant ":YutnoriFXApplication" as YutnoriFXApplication

User -> YutnoriApplication : startProgram()
YutnoriApplication -> User : requestUIType()
User -> YutnoriApplication : inputUIType()

alt if JavaFX selected
  YutnoriApplication -> YutnoriFXApplication : launchJavaFX()
  YutnoriFXApplication -> GameController : start()
  YutnoriFXApplication -> FXGameView : new FXGameView()
  FXGameView -> User : requestInfoForGame()
  User ->  FXGameView : UserInput()
  GameController -> FXGameView : getInfo()
  GameController -> FXGameView : requestRender()
  GameController -> FXGameView : connectButton()


else if Swing selected
  YutnoriApplication -> GameController : start()
  YutnoriApplication -> GameView : new GameView()
  GameView -> User : requestInfoForGame()
  User -> GameView : UserInput()
  GameController -> GameView : getInfo()
  GameController -> GameView : requestRender()
  GameController -> GameView : connectButton()
end alt

@enduml
