@startuml
title UC1: Game Initialization Sequence Diagram (JavaFX & Swing)

actor User
participant ":GameViewInterface" as GameViewInterface
participant ":GameController" as GameController
participant ":GameView" as GameView
participant ":YutnoriApplication" as YutnoriApplication
participant ":YutnoriFXApplication" as YutnoriFXApplication

User -> YutnoriApplication : startProgram()
YutnoriApplication -> User : requestUIType()
User -> YutnoriApplication : inputUIType()

alt if JavaFX selected
  YutnoriApplication -> YutnoriFXApplication : launchJavaFX()

  GameViewInterface -> User : requestInfoForGame()
  User ->  GameViewInterface : UserInput()
  GameController -> GameViewInterface : getInfo()
  GameController -> GameViewInterface : requestRender()
  GameController -> GameViewInterface : connectButton()


else if Swing selected
  GameView -> User : requestInfoForGame()
  User -> GameView : UserInput()
  GameController -> GameView : getInfo()
  GameController -> GameView : requestRender()
  GameController -> GameView : connectButton()
end alt

@enduml
