@startuml
title UC2: Throw Yut

actor Player
participant ":GameController" as GameController
participant ":GameViewInterface" as GameViewInterface
participant ":YutController" as YutController
participant List as stepQueue

Player -> GameViewInterface : press "Throw Yut" button

GameViewInterface -> YutController : throwYut(isRandom)

YutController -> GameViewInterface : return result
GameViewInterface -> GameController : return result

GameController -> stepQueue : add(result)
loop while result == 윷 or 모
    GameController -> Player : showMessage("윷/모입니다! 한 번 더 던지세요.")
	Player -> GameViewInterface : press "Throw Yut" button

    GameViewInterface -> YutController : throwYut(isRandom)

    YutController -> GameViewInterface : return result
    GameViewInterface -> GameController : return result
    GameController -> stepQueue : add(result)
end
ref over GameController,GameViewInterface
	UC3: movePiece
end ref

@enduml
