@startuml
title UC2: Throw Yut (JavaFX version)

actor Player
participant GameController as GameController
participant FXGameView as FXGameView
participant YutController as YutController
participant List as stepQueue

Player -> FXGameView : press "Throw Yut" button

FXGameView -> YutController : throwYut(isRandom)

YutController -> FXGameView : return result
FXGameView -> GameController : return result

GameController -> stepQueue : add(result)
loop while result == 윷 or 모
    GameController -> Player : showMessage("윷/모입니다! 한 번 더 던지세요.")
	Player -> FXGameView : press "Throw Yut" button

    FXGameView -> YutController : throwYut(isRandom)

    YutController -> FXGameView : return result
    FXGameView -> GameController : return result
    GameController -> stepQueue : add(result)
end
ref over GameController,FXGameView
	UC3: movePiece
end ref

@enduml
