@startuml
title UC2: Throw Yut Sequence Diagram

actor Player
participant GameController as GameController
participant GameView as GameView
participant YutController as YutController
participant List as stepQueue

Player -> GameView : press "Throw Yut" button

GameView -> YutController : throwYut(isRandom)

YutController -> GameView : return result
GameView -> GameController : return result

GameController -> stepQueue : add(result)

loop while result == 윷 or 모
    GameController -> Player : showMessage("윷/모입니다! 한 번 더 던지세요.")
	Player -> GameView : press "Throw Yut" button

    GameView -> YutController : throwYut(isRandom)

    YutController -> GameView : return result
    GameView -> GameController : return result
    GameController -> stepQueue : add(result)
end
ref over GameController,GameView
	UC3: movePiece
end ref
@enduml
