@startuml
title UC3: Move Piece

actor Player
participant ":GameViewInterface" as GameViewInterface
participant ":GameController" as GameController

loop while avaiableMove is not empty
GameViewInterface -> Player : displayAvailableMove()
Player-> GameController : giveMovePieceInfo()

ref over GameController
	UC4,5: Apply Board Movement Rule
end ref

GameController -> GameViewInterface : updateDisplay()
end loop

ref over GameController
	UC8: Check Victory Condition
end ref


@enduml
