@startuml
title UC3: Move Piece

actor Player
participant ":GameViewInterface" as GameViewInterface
participant ":GameController" as GameController
participant ":Board" as Board
participant ":Piece" as Piece

' Board 와 piece는 사용되지 않으므로 재검토 필요.

loop while avaiableMove is not empty
GameViewInterface -> Player : displayAvailableMove()
Player-> GameController : giveMovePieceInfo()
alt squareBoard
	ref over GameController
		UC4 : squareMovementRule
	end ref
else pentaBoard or hexaBoard
	ref over GameController
		UC4 : PentaBoard/HexaBoard Movement Rule
	end ref
end alt
GameController -> GameViewInterface : updateDisplay()
end loop

ref over GameController
	UC8: Check Victory Condition
end ref


@enduml
