@startuml
title UC3: Move Piece (JavaFX Version)

actor Player
participant FXGameView as FXGameView
participant GameController as GameController
participant Board as Board
participant Piece as Piece
participant Game as Game

loop while avaiableMove is not empty
FXGameView -> Player : displayAvailableMove()
Player-> GameController : giveMovePieceInfo()
alt squareBoard
	ref over GameController
		UC4 : squareMovementRule
	end ref
else pentaBoard or hexaBoard
	ref over GameController
		UC4 : PentaBoard/HexaBoard Movement Rule
	end ref
end alt
GameController -> FXGameView : updateDisplay()
end loop

ref over GameController
	UC8: Check Victory Condition
end ref


@enduml
