@startuml
title UC4: Apply SquareBoard Movement Rule

actor GameSystem
participant GameController
participant PieceMoveController
participant FXGameView
participant Piece
participant SquareBoard

GameSystem -> GameController : setMovementInfo()
GameController -> PieceMoveController : movePiece(piece, steps)

alt piece is not on board and steps > 0
	alt 빽도의 경우
    	PieceMoveController -> GameController : unableToMove()
    	GameController -> FXGameView : display("이동불가")
    else 도, 개, 걸, 윷, 모의 경우
    	PieceMoveController -> Piece : setOnBoard(true)
        PieceMoveController -> Piece : moveTo(nextPosition)
        Piece -> FXGameView : displayPosition()
    end alt

else if piece is on board
    alt 빽도의 경우
            PieceMoveController -> Piece : moveTo(nextPosition)
            alt piece is not finished
                ref over GameController, PieceMoveController
                	UC6 : Capture and Grouping
                end ref
            else piece at start
            	PieceMoveController -> Piece : setPieceFinished()
            end
    else 도, 개, 걸, 윷, 모의 경우
        PieceMoveController -> Piece : moveTo(nextPosition)
        Piece -> FXGameView : displayPosition()
        alt piece is not finished
            ref over GameController, PieceMoveController
            	UC6 : Capture and Grouping
            end ref
        end
    end
end

@enduml
