@startuml
title UC4: Apply SquareBoard Movement Rule


participant GameController
participant PieceMoveController
participant FXGameView
participant Piece
participant SquareBoard

GameController -> PieceMoveController : setMovementInfo()


alt piece is not on board and steps > 0
	alt 빽도의 경우
    	PieceMoveController -> GameController : unableToMove()
    	GameController -> FXGameView : display("이동불가")
    else 도, 개, 걸, 윷, 모의 경우
    	PieceMoveController -> Piece : setOnBoard(true)
        PieceMoveController -> Piece : moveTo(sideLinePosition)
        PieceMoveController -> Piece : finishCheck()
        Piece -> FXGameView : displayPosition()
    end alt

else if piece is on board
    alt 빽도의 경우
            PieceMoveController -> Piece : moveTo(nextPosition)
            PieceMoveController -> Piece : finishCheck()
            alt piece is not finished
                ref over GameController, PieceMoveController
                	UC6 : Capture and Grouping
                end ref
            end alt
    else 도, 개, 걸, 윷, 모의 경우
    	alt 외곽 순환
        	PieceMoveController -> Piece : moveTo(sideLinePosition)
        	PieceMoveController -> Piece : finishCheck()
        else 꼭짓점 도착
        	alt 마지막 꼭짓점이 아닐때
        		PieceMoveController -> Piece : moveTo(대각선으로 방향 변경)
        		PieceMoveController -> Piece : finishCheck()
        	end alt
       	else 중심점 도착
       		PieceMoveController -> Piece : moveTo(도착지점으로 방향 변경)
       		PieceMoveController -> Piece : finishCheck()
        end alt
        Piece -> FXGameView : displayPosition()
        alt piece is not finished
            ref over GameController, PieceMoveController
            	UC6 : Capture and Grouping
            end ref
        end
    end
end

@enduml
