@startuml
title UC6: Apply Special Rules - Capture and Grouping

participant ":GameController" as GameController
participant ":PieceMoveController" as PieceMoveController
participant ":Piece" as Piece
participant "EnemyPiece : Piece" as EnemyPiece
participant ":Cell" as Cell
participant ":Player" as Player


	GameController -> PieceMoveController: givePiecesInfo()
	PieceMoveController <- Cell : getPosition()

	loop while EnemyPiece is exist
		PieceMoveController -> EnemyPiece : reset()
		PieceMoveController -> Player : giveExtraTurn()
	end

	alt if PlayerPiece is exist
    	Piece -> Piece : StackPiece()
    end



@enduml
