@startuml
title UC7: Switch Turn


participant GameController
participant Game
participant GameViewInterface as View


GameController -> Game : checkTurnFinish()

alt if TurnFinish is true
	GameController -> Game : setNextPlayer()
	GameController -> View : updateDisplay()
end



@enduml
