@startuml

title UC8: Check Victory Condition

actor GameSystem
participant GameController


GameSystem -> GameController : endturn() # precondition 표시?
GameSystem -> GameController : checkFinish()

alt gameFinish == true
    ref over GameController, GameSystem
    	UC9: 게임 종료
    end ref
end
GameController --> GameSystem : continueGame()
@enduml
