@startuml

title UC8: Check Victory Condition

actor GameSystem
participant ":GameController" as GameController


GameSystem -> GameController : endturn()
' precondition 표시할지 말지 검토 필요
GameSystem -> GameController : checkFinish()

' 게임 종료는 alt가 아닌 break로 표현하였음
break gameFinish == true
    ref over GameController, GameSystem
    	UC9: 게임 종료
    end ref
end
GameController --> GameSystem : continueGame()
@enduml
