@startuml

title: UC9: Restart or Exit Game

actor Player
participant ":GameSystem" as GameSystem

GameSystem -> Player : displayVictory()
GameSystem -> Player : selectRestartOrExit()
Player -> GameSystem : pressButton()
alt if pressRestart
	ref over GameSystem , Player
		UC1 : 게임 시작
	end ref

end alt

@enduml
